version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: atlasmundi
      POSTGRES_PASSWORD: atlasmundi
      POSTGRES_DB: atlasmundi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlasmundi"]
      interval: 2s
      timeout: 3s
      retries: 30
