spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://ec2-3-217-251-77.compute-1.amazonaws.com:5432/ddfaoc99elhje8
    username: byekvuawiahlys
    password: adc933a2e63c8431ff32def7141d01d8a1046466270a03f0e567d2175fc4f5ad