management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    description: '@project.description@'

spring:
  application:
    name: atlasmundi
  main:
    banner-mode: log

  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connection-init-sql: set role atlasmundi

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
